use std::error::Error;

pub(crate) async fn run() -> Result<(), Box<dyn Error>> {
    Ok(())
}
